"""Add duration_hours to Course

Revision ID: 0b476969282f
Revises: 17e9072f6328
Create Date: 2025-12-15 21:33:08.462879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b476969282f'
down_revision = '17e9072f6328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('duration_hours')

    # ### end Alembic commands ###
