"""empty message

Revision ID: 3395fc787696
Revises: 0b476969282f
Create Date: 2025-12-15 21:41:56.164071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3395fc787696'
down_revision = '0b476969282f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')

    # ### end Alembic commands ###
